parameters:
    upload_directory: '%kernel.project_dir%/public/uploads/activites'
    profile_images_directory: '%kernel.project_dir%/public/uploads/profiles'
    publication_images_directory: '%kernel.project_dir%/public/uploads/publications'

services:
    _defaults:
        autowire: true
        autoconfigure: true

    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'

    App\Service\ActiviteService:
        arguments:
            $uploadDir: '%upload_directory%'